name: Parallel Jobs Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Starting Job 1"
      - run: sleep 10
      - run: echo "Finished Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - run: echo "Starting Job 2"
      - run: sleep 10
      - run: echo "Finished Job 2"