name: My First GitHub Workflow

on: push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Repository Files
        run: ls -la